wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697878168.5066
    t:
      1:
      - 55
      - 86
      - 95
      2:
      - 55
      - 86
      - 95
      3:
      - 23
      4: 3.11.2
      5: 0.15.12
      8:
      - 3
      - 5
      9:
        2: langchain
      13: windows-amd64
